apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-mailer-depl
  labels:
    app: ms-mailer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-mailer-backend
  template:
    metadata:
      labels:
        app: ms-mailer-backend
    spec:
      containers:
      - name: ms-mailer
        image: luisreciomelero/ms-quarkus-mailer:v1.0.1
        env:
          - name: KAFKA_HOST
            value: kafka:9092
          - name: SMTP_HOST
            value: "fakesmtp-svc"
          - name: SMTP_PORT
            value: "2525"
          - name: SMTP_MAIL_FROM
            value: "tfm.muirst.lrm@gmail.com"
          - name: SMTP_SSL
            value: "false"
          - name: SMTP_USERNAME
            value: "apikey"
          - name: SMTP_PASSWORD
            value: "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"
---

kind: Service
apiVersion: v1
metadata:
  name: ms-mailer
spec:
  type: ClusterIP
  selector:
    app: ms-mailer-backend
  ports:
  - port: 8090
    targetPort: 8090
  


