version: '3.5'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafkastreams-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:5.4.0
    hostname: kafka
    container_name: kafka
    networks:
      - kafkastreams-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9091:9091"
    environment:
      KAFKA_kafka_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      LISTENERS: PLAINTEXT://kafka:9092,LISTENER_EXTERNAL://localhost:9091,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://kafka:9092,LISTENER_EXTERNAL://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

  mg:
    image: luisreciomelero/mg-quarkus-producer:v1.0.8
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
    ports:
      - "8084:8084"
      
  ms:
    image: luisreciomelero/ms-quarkus-consumer:v1.0.1
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
      - postgres
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8086:8086"
      
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - kafkastreams-network  
    ports:
      - "5432:5432"
networks:
  kafkastreams-network:
    name: ks