version: '3.5'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafkastreams-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    hostname: kafka
    container_name: kafka
    networks:
      - kafkastreams-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9091:9091"
    environment:

      KAFKA_PORT: "9092"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_RESERVED_BROKER_MAX_ID: "1001"
  mg:
    #image: luisreciomelero/mg-quarkus-producer:v1.1.4
    image: luisreciomelero/mg-quarkus-producer:v1.2.1
    depends_on: 
      - zookeeper
      - kafka
  #    - msread
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      MSREAD_ADDRESS: "msread:8088"
    ports:
      - "8084:8084"  
  mscreate:
    #image: luisreciomelero/ms-quarkus-create:v1.0.6
    image: luisreciomelero/ms-quarkus-create-native:v1.0.5
    depends_on: 
      - zookeeper
      - kafka
      - postgres
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8086:8086"   
  msdelete:
    image: luisreciomelero/ms-quarkus-delete-native:v1.0.2
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8087:8087" 
  msread:
    image: luisreciomelero/ms-quarkus-read-native:v1.0.4
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8088:8088"
  msupdate:
    image: luisreciomelero/ms-quarkus-update-native:v1.0.2
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8089:8089" 
  msmailer:
    image: luisreciomelero/ms-quarkus-mailer:v1.0.1
    networks:
      - kafkastreams-network
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    environment:
      KAFKA_HOST: "kafka:9092"
     # KAFKA_HOST: "127.0.0.1:9091"
      SMTP_HOST: "fakesmtp"
      SMTP_PORT: "2525"
      SMTP_MAIL_FROM: "tfm.muirst.lrm@gmail.com"
      SMTP_SSL: "false"
      SMTP_USERNAME: "apikey"
      SMTP_PASSWORD: "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"
    ports:
      - "8090:8090"
  fakesmtp:
    image: luisreciomelero/fakesmtp:v1.0.1
    networks:
      - kafkastreams-network
    depends_on:
      - msmailer
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - kafkastreams-network  
    ports:
      - "5432:5432"
networks:
  kafkastreams-network:
    name: ks