version: '3.5'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafkastreams-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:5.4.0
    hostname: kafka
    container_name: kafka
    networks:
      - kafkastreams-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9091:9091"
    environment:
      KAFKA_kafka_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      LISTENERS: PLAINTEXT://kafka:9092,LISTENER_EXTERNAL://localhost:9091,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://kafka:9092,LISTENER_EXTERNAL://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

  mg:
    image: luisreciomelero/mg-quarkus-producer:v1.1.4
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
  #    - msread
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      MSREAD_ADDRESS: "msread:8088"
    ports:
      - "8084:8084"
      
  mscreate:
    image: luisreciomelero/ms-quarkus-create:v1.0.6
    #image: luisreciomelero/ms-quarkus-create-native:v1.0.1
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
      - postgres
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8086:8086"
      
  msdelete:
    image: luisreciomelero/ms-quarkus-delete:v1.0.3
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8087:8087"
      
  msread:
    image: luisreciomelero/ms-quarkus-read:v1.0.8
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8088:8088"
    
  msupdate:
    image: luisreciomelero/ms-quarkus-update:v1.0.2
    command: sh -c "sleep 60"
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    networks:
      - kafkastreams-network
    environment:
      KAFKA_HOST: "kafka:9092"
      POSTGRES_URL: "postgres:5432"
    ports:
      - "8089:8089" 
  
  msmailer:
    image: luisreciomelero/ms-quarkus-mailer:v1.0.1
    command: sh -c "sleep 60"
    networks:
      - kafkastreams-network
    depends_on: 
      - zookeeper
      - kafka
      - postgres
      - mscreate
    environment:
      KAFKA_HOST: "kafka:9092"
     # KAFKA_HOST: "127.0.0.1:9091"
      SMTP_HOST: "fakesmtp"
      SMTP_PORT: "2525"
      SMTP_MAIL_FROM: "tfm.muirst.lrm@gmail.com"
      SMTP_SSL: "false"
      SMTP_USERNAME: "apikey"
      SMTP_PASSWORD: "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"
    ports:
      - "8090:8090"
      
  fakesmtp:
    image: luisreciomelero/fakesmtp:v1.0.1
    networks:
      - kafkastreams-network
    depends_on:
      - msmailer
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - kafkastreams-network  
    ports:
      - "5432:5432"
networks:
  kafkastreams-network:
    name: ks