
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakesmtp-depl
  labels:
    app: mailer-app
    component: fakesmtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-app
      component: fakesmtp
  template:
    metadata:
      labels:
        app: mailer-app
        component: fakesmtp
        version: fakesmtp-v1
    spec:
      containers:
      - name: fakesmtp
        image: luisreciomelero/fakesmtp:v1.0.1
        ports:
        - containerPort: 2525
          name: smtp
          protocol: TCP
---

kind: Service
apiVersion: v1
metadata:
  name: fakesmtp
  labels:
    app: mailer-app
    component: fakesmtp
spec:
  type: ClusterIP
  selector:
    app: mailer-app
    component: fakesmtp
  ports:
  - port: 2525
    protocol: TCP
    targetPort: 2525
  





