 
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: kafka
    component: zookeeper
spec:
  ports:
  - port: 2181
    name: zookeeper-client
    #name: tcp-zookeeper
    targetPort: 2181
    protocol: TCP
  - port: 2888
    name: zookeeper-follower
    protocol: TCP
  - port: 3888
    name: zookeeper-leader
    protocol: TCP
  selector:
    app: kafka
    component: zookeeper