
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-vs
spec:
  hosts:
  - kafka
  http:
  - route:
    - destination:
        host: kafka
        port:
          number: 9092
    retries:
      attempts: 10
      perTryTimeout: 3s
      retryOn: 5xx,connect-failure
    timeout: 10s