apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
  labels:
    app: postgres-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dep
  template:
    metadata:
      labels:
        app: postgres-dep
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdatavol
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
      volumes:
        - name: pgdatavol
          hostPath:
            path: /pg/data
            type: DirectoryOrCreate

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres-dep
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30100


  

