apiVersion: v1
kind: ConfigMap
metadata:
  name: config-ms-delete
  namespace: default
data:
  database.max_size: "50"
  database.min_size: "1"
  kafka.host: kafka:9092
  postgres.host: "postgres:5432"
  
