
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-create-depl
  labels:
    app: crud-app
    component: ms-create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
      component: ms-create
  template:
    metadata:
      labels:
        app: crud-app
        component: ms-create
        version: ms-create-v1
    spec:
      containers:
      - name: ms-create
        image: luisreciomelero/ms-quarkus-create:v1.0.6
        #image: luisreciomelero/ms-quarkus-create-native:v1.0.1
        env:
          - name: KAFKA_HOST
            value: kafka:9092
          - name: POSTGRES_URL
            value: "postgres:5432"
---

kind: Service
apiVersion: v1
metadata:
  name: ms-create
  labels:
    app: crud-app
    component: ms-create
spec:
  type: ClusterIP
  selector:
    app: crud-app
    component: ms-create
  ports:
  - port: 8086
    targetPort: 8086
  


