apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-delete-depl
  labels:
    app: crud-app
    component: ms-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
      component: ms-delete
  template:
    metadata:
      labels:
        app: crud-app
        component: ms-delete
        version: ms-delete-v1
    spec:
      containers:
      - name: ms-delete
        image: luisreciomelero/ms-quarkus-delete:v1.0.5
        #image: luisreciomelero/ms-quarkus-delete-native:v1.0.1
        env:
          - name: KAFKA_HOST
            value: kafka:9092
          - name: POSTGRES_URL
            value: "postgres:5432"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 64Mi
        readinessProbe:
          exec:
            command:
              - curl 
              - "http://127.0.0.1:8087/health"
          initialDelaySeconds: 155
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - curl 
              - "http://127.0.0.1:8087/q/health/live"
          initialDelaySeconds: 120
          periodSeconds: 20
       

---

kind: Service
apiVersion: v1
metadata:
  name: ms-delete
  labels:
    app: crud-app
    component: ms-delete
spec:
  type: ClusterIP
  selector:
    app: crud-app
    component: ms-delete
  ports:
  - port: 8087
    #name: http-delete
    targetPort: 8087
  


