
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-update-depl
  labels:
    app: crud-app
    component: ms-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
      component: ms-update
  template:
    metadata:
      labels:
        app: crud-app
        component: ms-update
        version: ms-update-v1
    spec:
      containers:
      - name: ms-update
        #image: luisreciomelero/ms-quarkus-update:v1.0.2
        image: luisreciomelero/ms-quarkus-update-native:v1.0.1
        env:
          - name: KAFKA_HOST
            value: kafka:9092
          - name: POSTGRES_URL
            value: "postgres:5432"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 64Mi
        readinessProbe:
          exec:
            command:
              - curl 
              - "http://127.0.0.1:8089/q/health/ready"
          initialDelaySeconds: 155
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - curl 
              - "http://127.0.0.1:8089/q/health/live"
          initialDelaySeconds: 120
          periodSeconds: 20
        
---

kind: Service
apiVersion: v1
metadata:
  name: ms-update
  labels:
    app: crud-app
    component: ms-update
spec:
  type: ClusterIP
  selector:
    app: crud-app
    component: ms-update
  ports:
  - port: 8089
    targetPort: 8089
  


